[mypy]
exclude = (?x)(^gen/|^\.venv/)
python_version = 3.12
strict = True
warn_unreachable = True
mypy_path = legacy-sim/src:reconcile/src:report/src
explicit_package_bases = True
namespace_packages = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-shadowbook.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True
